---
title: 'A Guide to Applying Open Science Methods in Ecological Modeling'
date: "March 2024"
output: html_document
---

**<span style='color:red;'>Author Note</span>**:
This report was prepared by the authors as part of a series of projects related to ecological modeling in the US Army Corps of Engineers. However, this document represents only the opinions of the authors and not the USACE or any other organization. The document is shared in the spirit of open science and not as a product of any agency activities.


# **Abstract**

Transparency and accessibility are key parts of maintaining the integrity of reproducible science. Open Work is a philosophical approach for increasing the repeatability, quality, and shareability of a project, which is generally characterized by components of license, access, and format. Open science operationalizes Open Work by embracing best practices in the context of research and science-informed decision-making. Although some practices have been adopted, many aspects of Open Work and open science remain underutilized in ecosystem restoration. Within the realm of ecological modeling, open science practices can be used to streamline model development; benefiting model developers, model users, and other technical stakeholders. The goals of this paper are to: (1) describe the foundations of open science and its importance to USACE, (2) direct readers to resources for learning open science methods, and (3) demonstrate the value of open science methods in the context of USACE ecological modeling. Open science practices have the potential to improve the quality of USACE studies by increasing transparency, accessibility, and reproducibility, ultimately saving time and resources. 

# **Introduction**

Broadly speaking, ecological models “represent a system for the purposes of reproducing, simplifying, analyzing, or understanding it” (EC-1105-2-412). More practically, ecological models are conceptual and numerical tools used to predict ecological benefits and impacts of management actions. Models are developed through a five-step process of conceptualization, quantification, evaluation, application, and communication (Grant and Swannack 2008, Swannack et al. 2012, McKay et al. 2019). Transparent development allows for ecological models to be effectively integrated into management applications and embraced by stakeholders (van den Belt 2004, Swannack et al. 2012, Herman et al. 2019).

Transparency, replicability, and openness have emerged as fundamental issues across all aspects of ecological science, which can be redressed by sharing underlying data or removing access fees of publicly funded science (Powers and Hampton 2019). For instance, a White House task force was formed in May 2021 to “address short-term, high-priority actions to strengthen integrity and also lay [sic] the groundwork for longer-term coordination of Federal agency scientific efforts.” ([Scientific Integrity Task Force | The White House](https://www.whitehouse.gov/ostp/nstc/scientific-integrity-task-force/)). The concepts of openness and transparency are proposed in this report as an enabler of scientific integrity with a specific emphasis on “open science” policies and practices. 

Open Science practices may prove to be beneficial in the context of USACE project planning, decision-making and ecological modeling. Although the lexicon of open science may be new, the concepts build from long-term federal initiatives focused on upholding scientific integrity and increasing transparency in agency practices and decisions ([Holdren 2010](https://obamawhitehouse.archives.gov/administration/eop/ostp/library/scientificintegrity)). The objectives of this technical note are to: (1) describe the foundations of open science and its importance to ecological modeling, (2) direct readers to resources for learning open science methods, and (3) demonstrate the value of open science methods in the context of USACE ecosystem restoration planning.

# **What is Open Science?**

Open Science is characterized by transparent data collection processes, products, code, and metadata (Powers and Hampton 2019). The Center for Open Science has laid out goals of open science regarding the relevant parties involved throughout the collaborative research pipeline: scholarly service providers, institutions, funders, researchers, reviewers, librarians, and consumers. [Open Work is defined by the Open Knowledge and the Open Definition Advisory Council as a set of three key principles](https://opendefinition.org/od/2.1/en/) (taken verbatim):  

- Open License: The work must be available under an open license: freedom to use, build on, modify, and share.  
- Open Access: The work shall be available at no more than a reasonable one-time reproduction cost, preferably downloadable via the Internet without charge.  
- Open Format: The work must be provided in a convenient and modifiable form such that there are no unnecessary technological obstacles to the performance of the licensed rights. Specifically, data should be machine-readable, available in bulk, and provided in an open format or, at the very least, can be processed with at least one free/libre/open-source software tool.

	Open science is the set of policies, practices, and methods for delivering the three principles of Open Work. Open science exists on a continuum and can be adopted through a variety of practices tailored to a given application (Table 1). Every project and organization will have different levels of open science which they are trying to achieve, given a set of constraints such as time, resources, breadth of audience, available expertise, and security needs.

```{r echo=FALSE}
#Create empty table
Table01 <- as.data.frame(matrix(NA, nrow = 5, ncol = 4))
colnames(Table01) <- c("Hypothetical Scenario", "Open License", "Open Access", "Open Format")

#Specify rows of the table
Table01[1,] <- c("A USACE planning study is applying collaborative model development methods with a set of technical stakeholders to inform agency decision-making on a large, regional ecosystem restoration project. ", "High Degree of Open Licensing. The model can be used by anyone. Avoid forfeiting all copyright claims; attribution, virality, and liability were chosen with the model use and Authors’ discretion in mind.", "High Degree of Open Access. All model resources & data are readily available. Users may download model code, webapps, and documentation at no cost through online repositories (e.g., the ERDC Knowledge Core), . Model code development through shared repositories (e.g., GitHub).", "High Degree of Open Format. Documents are filed concisely with consistent and identifiable naming conventions. All documents and code follow widely accepted style guides, as applicable. All dependencies are free. ")
Table01[2,] <- c("A USACE planning study is developing a rapidly applicable ecological model to inform a small-scale restoration project through the Continuing Authorities Program.", "High Degree of Open Licensing. The model can be used by anyone. Avoid forfeiting all copyright claims; attribution, virality, and liability were chosen with the model use and Authors’ discretion in mind.", "Medium Degree of Open Access. Most model resources are readily available. Users may download model code at no cost through online repositories and GitHub. Model code development through GitHub.", "Medium Degree of Open Format. Documents are filed concisely with consistent and identifiable naming conventions. All documents and code follow community style guides. Some products require paid subscriptions, free through most institutions.")
Table01[3,] <- c("The USACE is collecting long-term ecological monitoring data at a series of sites supporting a major, regional ecosystem restoration initiative. ", "High Degree of Open Licensing. Licensing will be dependent on the repository or publisher of choice. ", "Medium Degree of Open Access. Most model resources are readily available. Users may download dataset through online repositories. No GitHub due to publishing conflict.", "Medium Degree of Open Format. Data and metadata are machine readable and curated. Can download as multiple file types.")
Table01[4,] <- c("A military installation is developing a set of ecological models to inform endangered species management.", "High Degree of Open Licensing. The study may contain sensitive information. Refer to the Technology Transfer Office. Follow guidelines for Controlled Unclassified Information (CUI).", "Medium Degree of Open Access. Some model resources are openly available, but most have restricted access. Model resources are stored on secure servers and locally as CUI.", "Medium Degree of Open Format. CUI documents are strictly formatted and labeled. The style and conventions of non-CUI are tailored to a handful of individuals who have access to the suite.")
Table01[5,] <- c("A USACE planning study is assessing the environmental impacts associated with navigation actions at a sensitive port facility.", "High Degree of Open Licensing. The study may contain sensitive information. Refer to the Technology Transfer Office. Follow CUI guidelines.", "Medium Degree of Open Access. No detailed model documents are available on the internet to avoid release of sensitive information. ", "Medium Degree of Open Format. Supporting documents follow strict guidelines, however, the model code is not well commented. ")

#Send output table rows into a single matrix
rownames(Table01) <- NULL
knitr::kable(Table01, caption="Table 1. Hypothetical examples of open science practices to achieve the goals of Open Work.", align="c") 
```

Implementation of open science requires commitment and resources that in turn pay dividends in the long term (e.g., for long duration projects, for multiple projects in series, or for the broader body of knowledge). Tools and methods used to practice open science vary depending on the scaling and specific project needs, and open science may be inappropriate in some instances (e.g., national defense, intellectual property). Accessibility in the framework of open science does not mean accessibility to everyone, rather, it is focused on a target audience such as relevant ERDC scientists or USACE project team members; presenting and creating technical tools that are fully accessible and understandable to all audiences is often infeasible.

# **Abstract**

Transparency and 


# **Abstract**

Transparency and 


# **Abstract**

Transparency and 


# **References Cited**

Grant W.E. and Swannack T.M. 2008. Ecological modeling: A common-sense approach to theory and practice. Malden, MA: Blackwell Publishing.

Fischenich, C. 2008. The application of conceptual models to ecosystem restoration. ERDC TN-EBA-TN-08-1. U.S. Army Engineer Research and Development Center, Vicksburg, MS.

Hampton, S.E., Anderson, S.S., Bagby, S.C., Gries, C., Han, X., Hart, E.M., Jones, M.B., Lenhardt, W.C., MacDonald, A., Michener, W.K. and Mudge, J., 2015. The Tao of open science for ecology. Ecosphere, 6(7), pp.1-13.

Herman BD, McKay SK, Altman S, Richards NS, Reif M, Piercy CD and Swannack TM (2019) Unpacking the Black Box: Demystifying Ecological Models Through Interactive Workshops and Hands-On Learning. Front. Environ. Sci. 7:122. Doi: 10.3389/fenvs.2019.00122

Langsdale, Stacy, Allyson Beall, Elizabeth Bourget, Erik Hagen, Scott Kudlas, Richard Palmer, Diane Tate, and William Werick, 2013. Collaborative Modeling for Decision Support in Water Resources: Principles and Best Practices. Journal of the American Water Resources Association (JAWRA) 49(3): 629-638. DOI: 10.1111/jawr.12065

McKay S.K. 2019. Visualization as a tool for ecological analysis. Encyclopedia of Ecology, 2nd Ed., Volume 2, pp. 213-220.  Eds. S. Jorgensen and B. Fath.  Doi:10.1016/B978-0-12-409548-9.10566-4.

McKay S.K., Richards N., and Swannack T.  2019.  Aligning ecological model development with restoration project planning.  ERDC EMRRP-SR-89.  U.S. Army Engineer Research and Development Center, Vicksburg, MS.

McKay S.K., Richards N., and Swannack T.M. 2022. Ecological model development: Evaluation of system quality.  ERDC/TN EMRRP-EBA-26.  U.S. Army Engineer Research and Development Center, Vicksburg, MS.

Michener, W.K., 2015. Ecological data sharing. Ecological informatics, 29, pp.33-44.

Powers, S.M. and Hampton, S.E., 2019. Open science, reproducibility, and transparency in ecology. Ecological Applications, 29(1), p.e01822.

Swannack, T. M., J. C. Fischenich, and D. J. Tazik. 2012. Ecological modeling guide for ecosystem restoration and management. ERDC/EL TR-12-18. Vicksburg, MS: US Army Engineer Research and Development Center.

U.S. Army Corps of Engineers (USACE).  2011.  Assuring quality of planning models.  EC-1105-2-412. Washington, DC.

Van den Belt, M. (2004). Mediated Modeling; A System Dynamics Approach to Environmental Consensus Building. Washington DC: Island Press.

Voinov, A., and Bousquet, F. (2010). Modeling with stakeholders. Environmental Modeling and Software, 25, 1268–1281. Doi: 10.1016/j.envsoft.2010.03.007.

Wickham H. and Bryan J. 2019. R packages: Organize, test, document, and share your code. https://r-pkgs.org/.
